//
//  Namespaces.h
//  CppRete
//
//  Created by Cory Slep on 9/23/13.
//  Copyright (c) 2013 Cory Slep. All rights reserved.
//

#ifndef CppRete_Namespaces_h
#define CppRete_Namespaces_h

#define EXPORT __attribute__((visibility("default")))

#define NAMESPACE_TUPLE Tuple
#define NAMESPACE_RETE Rete
#define NAMESPACE_ALG Algorithm
#define NAMESPACE_OVRHD Overhead

#define NAMESPACE_TUPLE_BEGIN namespace NAMESPACE_TUPLE {
#define NAMESPACE_TUPLE_END }

#define NAMESPACE_RETE_BEGIN namespace NAMESPACE_RETE {
#define NAMESPACE_RETE_END }

#define NAMESPACE_RETE_ALG_BEGIN NAMESPACE_RETE_BEGIN namespace NAMESPACE_ALG {
#define NAMESPACE_RETE_ALG_END NAMESPACE_RETE_END }
#define NAMESPACE_RETE_ALG NAMESPACE_RETE::NAMESPACE_ALG

#define NAMESPACE_TUPLE_ALG_BEGIN NAMESPACE_TUPLE_BEGIN namespace NAMESPACE_ALG {
#define NAMESPACE_TUPLE_ALG_END NAMESPACE_TUPLE_END }
#define NAMESPACE_TUPLE_ALG NAMESPACE_TUPLE::NAMESPACE_ALG

#define NAMESPACE_RETE_OVRHD_BEGIN NAMESPACE_RETE_BEGIN namespace NAMESPACE_OVRHD {
#define NAMESPACE_RETE_OVRHD_END NAMESPACE_RETE_END }
#define NAMESPACE_RETE_OVRHD NAMESPACE_RETE::NAMESPACE_OVRHD

#define NAMESPACE_TUPLE_OVRHD_BEGIN NAMESPACE_TUPLE_BEGIN namespace NAMESPACE_OVRHD {
#define NAMESPACE_TUPLE_OVRHD_END NAMESPACE_TUPLE_END }
#define NAMESPACE_TUPLE_OVRHD NAMESPACE_TUPLE::NAMESPACE_OVRHD

#endif
